-- Migration for environments that have legacy/partial multi-tenant tables.
-- This aligns the six core multi-tenant tables with api/schema-multitenant.sql.

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS role ENUM('super_admin','store_admin','ambassador') NOT NULL DEFAULT 'ambassador',
  ADD COLUMN IF NOT EXISTS store_id INT NULL,
  ADD COLUMN IF NOT EXISTS ambassador_id INT NULL,
  ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE stores
  ADD COLUMN IF NOT EXISTS name VARCHAR(190) NOT NULL DEFAULT 'Store',
  ADD COLUMN IF NOT EXISTS domain VARCHAR(190) NOT NULL,
  ADD COLUMN IF NOT EXISTS platform VARCHAR(50) NOT NULL DEFAULT 'shopify',
  ADD COLUMN IF NOT EXISTS owner_user_id INT NULL,
  ADD COLUMN IF NOT EXISTS default_commission_percent DECIMAL(5,2) NOT NULL DEFAULT 20.00,
  ADD COLUMN IF NOT EXISTS status VARCHAR(40) NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE ambassadors
  ADD COLUMN IF NOT EXISTS store_id INT NOT NULL,
  ADD COLUMN IF NOT EXISTS user_id INT NULL,
  ADD COLUMN IF NOT EXISTS name VARCHAR(190) NOT NULL DEFAULT 'Ambassador',
  ADD COLUMN IF NOT EXISTS email VARCHAR(190) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS phone VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS referral_code VARCHAR(120) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS status ENUM('pending','approved','paused','rejected') NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS commission_percent DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS approved_at DATETIME NULL;

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS store_id INT NOT NULL,
  ADD COLUMN IF NOT EXISTS ambassador_id INT NULL,
  ADD COLUMN IF NOT EXISTS referral_code VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS platform_order_id VARCHAR(190) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS customer_name VARCHAR(190) NULL,
  ADD COLUMN IF NOT EXISTS customer_email VARCHAR(190) NULL,
  ADD COLUMN IF NOT EXISTS amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS commission_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS payout_status VARCHAR(40) NOT NULL DEFAULT 'requested',
  ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE clicks
  ADD COLUMN IF NOT EXISTS store_id INT NOT NULL,
  ADD COLUMN IF NOT EXISTS ambassador_id INT NULL,
  ADD COLUMN IF NOT EXISTS referral_code VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS source VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS ip_hash VARCHAR(190) NULL,
  ADD COLUMN IF NOT EXISTS user_agent VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE payouts
  ADD COLUMN IF NOT EXISTS store_id INT NOT NULL,
  ADD COLUMN IF NOT EXISTS ambassador_id INT NOT NULL,
  ADD COLUMN IF NOT EXISTS amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS status ENUM('requested','approved','paid','rejected') NOT NULL DEFAULT 'requested',
  ADD COLUMN IF NOT EXISTS invoice_url VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS paid_at DATETIME NULL;
