ALTER TABLE stores ADD COLUMN IF NOT EXISTS public_url VARCHAR(255) NULL;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS contact_name VARCHAR(190) NULL;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS contact_email VARCHAR(190) NULL;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(50) NULL;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS contact_title VARCHAR(120) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS must_change_password TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE ambassadors ADD COLUMN IF NOT EXISTS payout_account VARCHAR(120) NULL;
ALTER TABLE payouts ADD COLUMN IF NOT EXISTS comment TEXT NULL;
ALTER TABLE payouts ADD COLUMN IF NOT EXISTS invoice_file_path VARCHAR(255) NULL;
